### ISSUE TITLE
Undeclared dependency DateTime?

### ISSUE THREAD

**Issue by eserte** [szabgab/CPAN-Digger#19]
It seems that DateTime needs to be declared as a prerequisite --- the test suite fails on some systems because of a missing DateTime.pm. See for example http://www.cpantesters.org/cpan/report/13049926-2526-11eb-950a-33741f24ea8f

**Comment by szabgab** [comment]
Thanks for reporting. I should really run the CI on a plain Perl without any modules installed.

**Comment by eserte** [comment]
I think a good approach is to have at least one CI configuration which is just using the system perl and cpanminus.

**Comment by szabgab** [comment]
My plan is to create a tarball artifact and then in a separate job use a plain perl or system perl as you suggested and install from the tarball.
