### ISSUE TITLE
Stats ribbon-menu-item gets 500 error 

### ISSUE THREAD

**Issue by n1vux** [szabgab/CPAN-Digger#34]
To Reproduce: 

On [homepage](https://cpan-digger.perlmaven.com/), click [Stats](https://cpan-digger.perlmaven.com/recent/stats) to the right of Rocks. 

Result: `500 Internal Server Error`

**Comment by szabgab** [comment]
Apparently the correct way to serve pages without .html ending in nginx is this:

```
try_files $uri.html $uri $uri/ =404;
```

and not what I had.

So now at least the page gives 404. That's better.

**Comment by szabgab** [comment]
And now the link has been removed as well. Thanks for reporting.
